-- Implement a program to make change. Your
-- program should accept a list of numbers
-- on stdin. The first number indicates the
-- amount of money to change, the rest
-- indicate the demoninations of coin to
-- make change into.
--
-- The program should print out a list of
-- coins in the demoninations given that totals
-- up to the amount of money being changed.
-- If there is money left over (i.e. the money
-- cannot be divided evenly into the demoninations
-- given), the program should print the list of
-- coins and a message indicating how much
-- was left unchanged.
--
